apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-microservice
  labels:
    app: demo-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-microservice
  template:
    metadata:
      labels:
        app: demo-microservice
    spec:
      containers:
        - name: app
          image: <ACR_LOGIN_SERVER>/demo-microservice:latest
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5

